---
- name: This is a playbook to test out connecting to ovirt
  hosts: localhost
  gather_facts: False

  collections:
    - community.kubernetes

  roles:
    - provision
    - integration
  
  environment:
    K8S_AUTH_KUBECONFIG: ./{{ cluster_name }}/auth/kubeconfig